### ISSUE TITLE
libPocoXML.so.71: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by z772** [hello2all/gamma-ray#2]
Hi, i want to contribute if i can. I followed the insructions but get this final error 

./main: error while loading shared libraries: libPocoXML.so.71: cannot open shared object file: No such file or directory

Any fixes for this?

Regards

**Comment by hello2all** [comment]
Hi, please make sure you have the `gamma-ray.json` config file in the same directory as the executable. If you followed the instruction it should be in your `/release` folder

**Comment by z772** [comment]
I do

./main: error while loading shared libraries: libPocoXML.so.71: cannot open shared object file: No such file or directory
ubuntu@ip:~/gamma-ray/release$ ls
CMakeCache.txt              Doxyfile               gamma-ray.json
CMakeDoxyfile.in            Testing                main
CMakeDoxygenDefaults.cmake  build.ninja            tests
CMakeFiles                  cmake_install.cmake    unit_tests
CTestTestfile.cmake         compile_commands.json
DartConfiguration.tcl       config.h
ubuntu@ip:~/gamma-ray/release$ ./main 
./main: error while loading shared libraries: libPocoXML.so.71: cannot open shared object file: No such file or directory
ubuntu@ip:~/gamma-ray/release$ cd ../
ubuntu@ip:~/gamma-ray$ ./release/main 
./release/main: error while loading shared libraries: libPocoXML.so.71: cannot open shared object file: No such file or directory

**Comment by z772** [comment]
When i ran "source" command on build poco i got "No file argument supplied"

**Comment by z772** [comment]
sent you an email

**Comment by hello2all** [comment]
ok, I found the problem. It’s my fault, there is a deprecated config param I forgot to remove from the source. Here's a temporary fix, replace the default config file with the following:

```json
{
  "websocketUrl": "wss://testnet.bitmex.com/realtime",
  "httpUrl": "https://testnet.bitmex.com",
  "apiKey": "iCDc_MrgK2bfZOaRKhz5K99A",
  "apiSecret": "VJN9dBwrBInY2dY-SMVzDkb1suv9DQRwxmYKiEh7TcJVTg0w",
  "contract": "XBTUSD",
  "quotingParam": {
    "quotingMode": "AvellanedaStoikov",
    "size": 300,
    "quotingModeParam": {
      "AvellanedaStoikov": {
        "gamma": 0.1,
        "sigma": 0.025,
        "k": 0.11593
      },
      "Top": {
        "spread": 0.5
      },
      "Mid": {
        "spread": 0.5
      }
    },
    "pairs": 1,
    "priceInterval": 0.5,
    "sizeIncrement": 0,
    "targetBasePosition": 0,
    "positionOffset": 100000,
    "skewFactor": 0,
    "tradesPerMinute": 5,
    "tradeRateSeconds": 60
  }
}
```
Note the deprecated `tradeRateSeconds` param, you can set anything as it doesn't have any impact. Just keep it there will prevent this error from occurring.

Will work on proper fix latter

**Comment by z772** [comment]
This doesn't relly solve the issue terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be number, but is null
Aborted (core dumped)

**Comment by z772** [comment]
> This doesn't relly solve the issue terminate called after throwing an instance of 'nlohmann::detail::type_error'
> what(): [json.exception.type_error.302] type must be number, but is null
> Aborted (core dumped)

I ran sudo apt install libpoco-dev and then that happened

**Comment by hello2all** [comment]
run `./run-release.sh`

**Comment by z772** [comment]
yeah, lol i see, i was trying to run it on live net not testnet. Thanks 
brother, i hope we can make this great.

How do i run it on mainnet?
