### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by Sacror** [hello2all/gamma-ray#9]
![Screenshot from 2021-12-20 07-44-08](https://user-images.githubusercontent.com/51163501/146731660-a5eebaa2-a8e2-4566-b2df-a3816a0b0ee1.png)

**Comment by prgtrdr** [comment]
Insert (void) at beginning of line 63 in bitmexws.cpp. Corrected line is:

`  (void)std::async(std::launch::async, [this]() { this->maintain_heartbeat(); });`
